---
- name:  Install nginx Server
  hosts: Nginx
  become: yes

  tasks:
    - name: Install nginx
      apt: 
        name: nginx
        state: present

    - name: nginx enable
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Add git repository
      git:
        repo: https://github.com/AlexandrNeverov/page
        dest: /var/www/html
        force: yes
        clone: yes